version: "3.9"

services:
  odoo-app:
    container_name: odoo-app-${STAGE_DOMAIN:-staging.domain.com}
    ports:
      - "${APP_PORT:-8069}:8069"
      - "${CHAT_PORT:-8072}:8072" # live chat
    networks:
      - caddy
    labels:
      caddy: ${STAGE_DOMAIN:-domain.com}
      caddy.reverse_proxy: "http:hypercorevn-1.hophamlam.com:10016"
      caddy.reverse_proxy_1: "/longpolling/* http:hypercorevn-1.hophamlam.com:20016"
      caddy.reverse_proxy.header_up: "X-Forwarded-Proto https"
      caddy.reverse_proxy.header_up_1: "X-Forwarded-Host {host}"
      caddy.reverse_proxy.header_up_2: "X-Url-Scheme {scheme}"
      caddy.reverse_proxy.header_up_3: "X-Real-IP {remote}"
      # caddy.encode: "gzip zstd"
      caddy.header: "/ {Content-Security-Policy 'upgrade-insecure-requests;'}"
      # caddy.file_server:
      # caddy.log:

  postgres-db:
    container_name: postgres-db-${STAGE_DOMAIN:-staging.domain.com}
    networks:
      - caddy

networks:
  caddy:
    external: true
