version: '3.9'

networks:
  odoo-gaolamthuy-prod:
    name: odoo-gaolamthuy-prod
    driver: bridge

services:
  odoo-gaolamthuy-prod-db:
    container_name: odoo-gaolamthuy-prod-db
    image: postgres:15
    networks:
      - odoo-gaolamthuy-prod
    user: root
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo-gaolamthuy-prod-app:
    container_name: odoo-gaolamthuy-prod-app
    image: odoo:16
    networks:
      - odoo-gaolamthuy-prod
    user: root
    depends_on:
      - odoo-gaolamthuy-prod-db
    # ports:
    #   - "10016:8069"
    #   - "20016:8072" # live chat
    expose: 
      - "8069"
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=odoo-gaolamthuy-prod-db
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service