version: "3.9"

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:${PG_VERSION:-15}
    user: root
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-my-odoo}
      - POSTGRES_USER=${DB_USER:-my-odoo}
      - POSTGRES_DB=postgres-db
    networks:
      - caddy
    restart: always # run as a service
    volumes:
      - .././postgresql:/var/lib/postgresql/data

  odoo-app:
    container_name: odoo-app
    image: odoo:${ODOO_VERSION:-16}
    user: root
    depends_on:
      - postgres-db
    ports:
      - "10016:8069"
      - "20016:8072" # live chat
    networks:
      - caddy
    tty: true
    command: --
    #    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=postgres-db
      - USER=${DB_USER:-my-odoo}
      - PASSWORD=${DB_PASSWORD:-my-odoo}
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - .././addons:/mnt/extra-addons
      - .././etc:/etc/odoo
    restart: always # run as a service

networks:
  caddy:
    external: true
