name: production deploy
on:
  # pull_request:
  #   branches: 
  #     - main
  #   types: [closed]
  push:
    branches:
      - main

jobs:
  prod-deploy:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: git pull && docker-compose up
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo git -C ~/${{ github.event.repository.name }}-prod restore .
            sudo git -C ~/${{ github.event.repository.name }}-prod pull 
            sudo docker-compose -f ~/${{ github.event.repository.name }}-prod/docker-compose.prod.yml -p "odoo-gaolamthuy-prod" up --build --force-recreate -d