name: test deploy on staging stack
on:
  push:
    branches:
      - main

jobs:
  test-stage:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: git pull && docker-compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_STAGE }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |

            # Add any additional deployment commands
            sudo echo "Deploying via SSH..."
            git -C './${{ github.event.repository.name }}' pull || git clone https://github.com/${{github.repository}}.git './${{ github.event.repository.name }}'

            # Checkout to main branch
            cd ~/${{ github.event.repository.name }}
            git checkout main

            # Remove the old .env file if it exists
            sudo rm -f ~/${{ github.event.repository.name }}/.env
            # Create a new .env file with secrets
            echo "${{ secrets.DOTENV }}" | sudo tee -a ~/${{ github.event.repository.name }}/.env

            # Add any additional commands for deployment
            sudo docker system prune -f
            sudo docker image prune -a --force
            docker compose -p my-odoo-v16 -f docker/docker-compose.stage.yml up -d
            echo "done"
