name: test deploy on staging stack
on:
  push:
    branches:
      - staging

jobs:
  test-stage:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: git pull && docker-compose up
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo git -C ~/${{ github.event.repository.name }}-stage restore .
            sudo git -C ~/${{ github.event.repository.name }}-stage pull 
            sudo docker-compose -f ~/${{ github.event.repository.name }}-stage/docker-compose.stage.yml -p "odoo-gaolamthuy-stage" up --build --force-recreate -d