name: test deploy on staging stack
on:
  push:
    branches:
      - main

jobs:
  test-stage:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: git pull && docker-compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_STAGE }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |

            # Add any additional deployment commands
            sudo echo "Deploying via SSH..."
            git -C './${{ github.event.repository.name }}-stage' pull origin main || git clone -b main https://github.com/${{github.repository}}.git './${{ github.event.repository.name }}-stage'

            # Checkout to main branch
            cd ~/${{ github.event.repository.name }}-stage

            # Create folders
            mkdir -p postgresql/
            mkdir -p etc/
            mkdir -p addons/

            # Gain permisson for all folder
            sudo chmod -R 777 postgresql/
            sudo chmod -R 777 etc/
            sudo chmod -R 777 addons/

            # Remove the old .env file if it exists
            sudo rm -f .env
            # Create a new .env file with secrets
            echo "${{ secrets.DOTENV }}" | sudo tee -a .env

            # Run docker compose as staging
            docker compose -p ${{ github.event.repository.name }}-stage -f ./docker-compose.yml -f ./docker-compose.stage.yml up -d --build --force-recreate

            docker system prune --volumes --force

            sudo chmod -R 777 postgresql/

            echo "done"
