name: remote ssh command
on:
  pull_request:
    branches: 
      - main
    types: [closed]
  push:
    branches:
      - main
      - staging

jobs:
  my-action:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: git pull && docker-compose up
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo git -C ~/${{ github.event.repository.name }} restore .
            sudo git -C ~/${{ github.event.repository.name }} pull 
            sudo docker-compose -f ~/gaolamthuy-odoo16/docker-compose.stage.yml -p "odoo-gaolamthuy-stage" up --build --force-recreate -d